# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "demo_xProject" do
pod "xProject",:git=> 'git@github.com:Lwgfangz/xProject.git'
end

target "demo_xProjectTests" do

end

