# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "demo_引用自己的bsjsonaddition库" do

pod "bsjsonadditions",:git=> 'git@github.com:Lwgfangz/bsjsonadditions.git'
end

target "demo_引用自己的bsjsonaddition库Tests" do

end

